version: "3"
services:
  postgres:
    container_name: postgres
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - ./data/postgres-data:/var/lib/postgresql/data

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    logging:
      driver: none

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3-management
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest

  nginx:
    depends_on:
      - users
      - email-service
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - "3050:3050"

  users:
    container_name: users
    build:
      dockerfile: Dockerfile.dev
      context: ./users
    ports:
      - 4000:4000
    volumes:
      - ./users:/app
      - /app/node_modules
    depends_on:
      - postgres
    env_file:
      - .env

  email-service:
    container_name: email-service
    build:
      dockerfile: Dockerfile.dev
      context: ./email
    ports:
      - 4001:4001
    volumes:
      - ./email:/app
      - /app/node_modules
    env_file:
      - .env
